Terraform Example Code Optimized
terraform-ibm-modules/terraform-ibm-security-group pull request #242
Opened 2024-02-21 23:35 UTC by marifse

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-21 23:36 UTC, marifse commented
@ocofaigh can you please have a look at this pull request, and let me know your feedback.

2024-03-19 12:52 UTC, marifse commented
@ocofaigh please review it too. Thanks

2024-03-20 16:11 UTC, marifse commented
@ocofaigh can you please look into this, and approve if all okay.

2024-03-26 14:48 UTC, ocofaigh commented on examples/sg-target-example/catalogValidationValues.json.template
> +}
please delete this file

2024-03-26 14:48 UTC, ocofaigh commented on examples/default/catalogValidationValues.json.template
> +}
please delete this file

2024-03-26 14:49 UTC, ocofaigh commented
@marifse I left 2 comments

2024-03-26 14:49 UTC, ocofaigh commented
/run pipeline

2024-03-26 15:43 UTC, ocofaigh commented
/run pipeline

2024-03-26 16:05 UTC, ocofaigh commented
@marifse Test failed with:
```
TestRunDefaultExampleWithoutIBMRules 2024-03-26T15:50:47Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: No value for required variable
│ 
│   on variables.tf line 99:
│   99: variable "vpc_name" {
│ 
│ The root module input variable "vpc_name" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a value for
│ this variable.
╵}
```

2024-03-27 18:01 UTC, ocofaigh commented
@marifse Just to be clear, you wont need to add any `catalogValidationValues.json.template` files if they don't already exist. If they do exist, just ensure that all required variables for the example are in them.

2024-03-28 09:29 UTC, marifse commented
> @marifse Just to be clear, you wont need to add any new `catalogValidationValues.json.template` files if they don't already exist. If they do exist, just ensure that all required variables for the example are in them.

@ocofaigh done

2024-03-29 11:52 UTC, ocofaigh requested changes
see comments

2024-03-29 11:52 UTC, ocofaigh commented on examples/default/main.tf
> +  name              = "${var.prefix}-vpc"
dont use the prefix here too. set it to `name = "vpc"`

2024-03-29 11:52 UTC, ocofaigh commented on examples/sg-target-example/main.tf
> +  name              = "${var.prefix}-vpc"
dont use the prefix here too. set it to `name = "vpc"`

2024-03-29 13:21 UTC, marifse commented
@ocofaigh fixed, please check now

2024-04-03 16:13 UTC, ocofaigh commented
@marifse 
![image](https://github.com/terraform-ibm-modules/terraform-ibm-security-group/assets/29608224/ec2e83cf-5679-4c44-8337-28c1344b74c2)

2024-04-03 20:50 UTC, marifse commented
@ocofaigh please check now and rerun. conflicts resolved

2024-04-03 20:51 UTC, marifse commented
@ocofaigh please check now and rerun. conflicts resolved

2024-04-05 14:10 UTC, ocofaigh approved these changes

2024-04-05 14:11 UTC, merged

2024-06-11 08:43 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.6.2 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-security-group/releases/tag/v2.6.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: